VUNuTsSerEDbkRUFMaYG = '99999999'
Password﻿ = 'VUNuTsSerEDbkRUFMaYG'
PS = gg.prompt({'✅Giriş Paneli✅'},{[1]=''},{[1]='text'})
if not PS the﻿n os.exit() 
end 
if PS[1] == Password then 
gg.toast('Key Doğrulandı')
gg.alert("❤️Hoş Geldiniz Efendim❤️")
else 
gg.alert('Geçersiz Anahtar\n⚠️Admin Değilsin⚠️') os.exit() end

if os.date("%Y%m%d") > VUNuTsSerEDbkRUFMaYG then
  hh = gg.alert("⛔ Key Süreniz Dolmuştur ⛔")
  os.exit()
end




os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.clearResults()
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620,137,442,967,552")
gg.refineNumber("620,137,442,967,552")
gg.getResults(50000)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620,137,442,967,552")
gg.refineNumber("620,137,442,967,552")
gg.getResults(50000)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("578351706144768;564058054983680")
gg.refineNumber("578351706144768")
gg.getResults(50000)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.searchNumber("577252194516992;288233678981562368")
gg.refineNumber("577252194516992")
gg.getResults(50000)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("17,592,186,044,416~288233678981562368;288233678981562368;288232579469934592")
gg.refineNumber("17,592,186,044,416~288233678981562368")
gg.getResults(50000)
gg.editAll("67109633", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("134658;131586")
gg.refineNumber("134658")
gg.getResults(50000)
gg.editAll("135682", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("133378;262403")
gg.refineNumber("133378")
gg.getResults(50000)
gg.editAll("135682", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("134914;144387")
gg.refineNumber("134914")
gg.getResults(50000)
gg.editAll("135682", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("131842;132098")
gg.refineNumber("131842")
gg.getResults(50000)
gg.editAll("135682", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("133634;135682")
gg.refineNumber("133634")
gg.getResults(50000)
gg.editAll("135682", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620137442967552")
gg.refineNumber("620137442967552")
gg.getResults(510)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("620137442967552")
gg.refineNumber("620137442967552")
gg.getResults(5010)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("578351706144768;564058054983680")
gg.refineNumber("578351706144768")
gg.getResults(50010)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.searchNumber("577252194516992;288233678981562368")
gg.refineNumber("577252194516992")
gg.getResults(50010)
gg.editAll("288233678981562368", gg.TYPE_QWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("3298534883328~288233678981562368;288233678981562368")
gg.refineNumber("3298534883328~288233678981562368")
gg.getResults(5678)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("280~590336;67109633")
gg.refineNumber("280~590336")
gg.getResultsCount()
gg.clearList()
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":l_report", nil, nil, nil, nil, nil)
gg.getResults(85555)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_rcv_anti_data", nil, nil, nil, nil, nil)
gg.getResults(85555)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearList()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/report", nil, nil, nil, nil, nil)
gg.refineNumber(":/report")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cheat", nil, nil, nil, nil, nil)
gg.refineNumber(":cheat")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":Cheat", nil, nil, nil, nil, nil)
gg.refineNumber(":Cheat")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/tss", nil, nil, nil, nil, nil)
gg.refineNumber(":/tss")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":/report", nil, nil, nil, nil, nil)
gg.refineNumber(":/report")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":cheat", nil, nil, nil, nil, nil)
gg.refineNumber(":cheat")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":Cheat", nil, nil, nil, nil, nil)
gg.refineNumber(":Cheat")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":/tss", nil, nil, nil, nil, nil)
gg.refineNumber(":/tss")
gg.getResults(99999)
gg.clearResults()
os.remove("/mnt/shell/0/emulated/Android/data/com.pubg.krmobile/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.pubg.krmobile/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.tmgp.pubgmhd/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.tmgp.pubgmhd/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.tmgp.pubgmhd/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.tmgp.pubgmhd/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.vng.pubgmobile/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.vng.pubgmobile/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.vng.pubgmobile/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.ig/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.ig/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.igce/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.igce/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.igce/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.igce/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.igce/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/mnt/shell/0/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/sdcard/Android/data/com.tencent.iglite/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate/SaveGames/JKGuestRegisterCnt.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppBaseConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AppConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AudioPluginConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/BuildConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/CustomDeviceList.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceProfiles.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/DeviceSwitchers.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/EditorPerProjectUserSettings.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Engine.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Game.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/GameUserSettings.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Hardware.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IMSDKConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Input.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/LogSuppression.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/MidasConfig.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OBHttp.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/OpenIDCommand.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/PufferDownloader.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Scalability.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/ServerSwitch.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UAE.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/Updater.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserCustom.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserSettings.ini")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/CommonSaveGame_4126599880770857.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/LeagueStatue.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/loginInfoFile.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/MailPhoneLogin.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4123188938540329.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/personalprefs_4126599880770857.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/playerprefs.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4123188938540329.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/RecruitFilterSetting_4126599880770857.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/business_res_download_priority_table_new")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/cadge_table")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/dubber_table_ext")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/easy_buy_cfg")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_award_table")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/mentor_task_table")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/new_level_task_cover_table")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/social_authorize_config")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/upgrade_parameter")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json")
os.remove("/storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json")
gg.clearResults()
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/cache")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/login-identifier.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/vmpcloudconfig.json")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.toast("Offline Ban Fix %50 🛡️")
gg.clearList()
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f81fec,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f81fdc,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f81fe4,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f81ff0,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f58,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f5c,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f60,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f64,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f68,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f6c,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f70,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f74,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f78,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f7c,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f80,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f84,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f88,['flags'] = 16,['value'] = 0,},})
gg.getRangesList("libtersafe.so")
gg.setValues({[1] = {['address'] = 0xe4f51f8c,['flags'] = 16,['value'] = 0,},})
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
os["remove"]((";com.tencent.ig"))
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.tencent.ig", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
os["remove"]((";com.pubg.krmobile"))
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["setRanges"](gg["REGION_C_ALLOC"])
gg["searchNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["setVisible"](false)
gg["refineNumber"](";com.pubg.krmobile", gg["TYPE_DOUBLE"])
gg["getResults"](99999)
gg["editAll"]("0", gg["TYPE_FLOAT"])
gg["setVisible"](false)
gg["clearResults"]()
gg["sleep"](1000)
gg["setVisible"](false)
gg["clearResults"]()
gg.setRanges(gg.REGION_C_ALLOC)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber(";com.tencent.ig", gg.TYPE_DOUBLE, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.clearResults()
gg.toast("Ofline Ban Fix Bypass %100 🛡️")
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("16384;4448", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber("4448", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(99900000)
gg.editAll("2225", gg.TYPE_DWORD)
gg.getResultsCount()
gg.getResults(99900000)
gg.editAll("1337", gg.TYPE_DWORD)
gg.getResults(99900000)
gg.getResults(99900000)
gg.addListItems({[1] = {address = 2867203428,flags = 4,freeze = true,value = 1337}})
gg.clearResults()
os.remove("src/main/java/com/google/errorprone/annotations")os.remove("src/main/java/com/google/errorprone/annotations")os.remove("src/main/java/com/google/errorprone/annotations/concurrent")os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")gg.clearResults()gg.setVisible(false)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("620,137,442,967,552", gg.TYPE_QWORD)gg.refineNumber("620,137,442,967,552", gg.TYPE_QWORD)gg.getResults(50000)gg.editAll("288233678981562368", gg.TYPE_QWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("620,137,442,967,552", gg.TYPE_QWORD)gg.refineNumber("620,137,442,967,552", gg.TYPE_QWORD)gg.getResults(50000)gg.editAll("288233678981562368", gg.TYPE_QWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("578351706144768;564058054983680", gg.TYPE_QWORD)gg.refineNumber("578351706144768", gg.TYPE_QWORD)gg.getResults(50000)gg.editAll("288233678981562368", gg.TYPE_QWORD)gg.clearResults()gg.setVisible(false)gg.searchNumber("577252194516992;288233678981562368", gg.TYPE_QWORD)gg.refineNumber("577252194516992", gg.TYPE_QWORD)gg.getResults(50000)gg.editAll("288233678981562368", gg.TYPE_QWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("17,592,186,044,416~288233678981562368;288233678981562368;288232579469934592", gg.TYPE_QWORD)gg.refineNumber("17,592,186,044,416~288233678981562368", gg.TYPE_QWORD)gg.getResults(50000)gg.editAll("67109633", gg.TYPE_DWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("134658;131586", gg.TYPE_DWORD)gg.refineNumber("134658", gg.TYPE_DWORD)gg.getResults(50000)gg.setVisible(false)gg.editAll("135682", gg.TYPE_DWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("133378;262403", gg.TYPE_DWORD)gg.refineNumber("133378", gg.TYPE_DWORD)gg.getResults(50000)gg.setVisible(false)gg.editAll("135682", gg.TYPE_DWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("134914;144387", gg.TYPE_DWORD)gg.refineNumber("134914", gg.TYPE_DWORD)gg.getResults(50000)gg.setVisible(false)gg.editAll("135682", gg.TYPE_DWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("131842;132098", gg.TYPE_DWORD)gg.refineNumber("131842", gg.TYPE_DWORD)gg.getResults(50000)gg.editAll("135682", gg.TYPE_DWORD)gg.clearResults()gg.setRanges(gg.REGION_C_ALLOC)gg.setVisible(false)gg.searchNumber("133634;135682", gg.TYPE_DWORD)gg.refineNumber("133634", gg.TYPE_DWORD)gg.setVisible(false)gg.getResults(50000)gg.editAll("135682", gg.TYPE_DWORD)gg.clearResults()
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/cache")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/login-identifier.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json")
os.remove("/storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/cache/GCloud.ini")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/vmpcloudconfig.json")
os.remove("/storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations")
os.remove("src/main/java/com/google/errorprone/annotations/concurrent")
os.remove("third_party.java_src.error_prone.project.annotations.Google_internal")
gg.alert("🛡️𝐁𝐘𝐏𝐀𝐒𝐒 %100 𝐀𝐊𝐓İ𝐅, 𝐖İ𝐍 𝐒𝐒 @𝐄𝐁𝐇𝐒𝐇𝐏 .🛡️")
